import re
import pyperclip
def replace_integer_value_of(text):
    # Regular expression to match `Integer.valueOf(Z)` where Z is a single letter
    pattern = r"Integer\.valueOf\((\w)\)"
    # Replacement pattern to double the letter
    replacement = r"Integer.valueOf(\1\1)"
    # Perform the substitution
    return re.sub(pattern, replacement, text)

# Example usage
input_text = """
 Integer[][] wingFacePerms = { { Integer.valueOf(B), Integer.valueOf(C), Integer.valueOf(D), Integer.valueOf(A),
                Integer.valueOf(Q), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(E),
                Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(I), Integer.valueOf(Z),
                Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(M), Integer.valueOf(Z), Integer.valueOf(Z),
                Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(D), Integer.valueOf(A), Integer.valueOf(B), Integer.valueOf(C), Integer.valueOf(I),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(M),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Q),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(E),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(C), Integer.valueOf(D), Integer.valueOf(A), Integer.valueOf(B), Integer.valueOf(M),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Q),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(E),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(I),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(P), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(C), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(J),
                        Integer.valueOf(K), Integer.valueOf(L), Integer.valueOf(I), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(U), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(F),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(F), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(U), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(L),
                        Integer.valueOf(I), Integer.valueOf(J), Integer.valueOf(K), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(C), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(P),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(U), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(P), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(K),
                        Integer.valueOf(L), Integer.valueOf(I), Integer.valueOf(J), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(F), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(C),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(T), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(B), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(N),
                        Integer.valueOf(O), Integer.valueOf(P), Integer.valueOf(M), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(V), Integer.valueOf(Z),
                        Integer.valueOf(J), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(J), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(V), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(P),
                        Integer.valueOf(M), Integer.valueOf(N), Integer.valueOf(O), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(B), Integer.valueOf(Z),
                        Integer.valueOf(T), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(V), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(T), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(O),
                        Integer.valueOf(P), Integer.valueOf(M), Integer.valueOf(N), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(J), Integer.valueOf(Z),
                        Integer.valueOf(B), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(L), Integer.valueOf(F),
                        Integer.valueOf(G), Integer.valueOf(H), Integer.valueOf(E), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(X), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(D), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(R) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(R), Integer.valueOf(H),
                        Integer.valueOf(E), Integer.valueOf(F), Integer.valueOf(G), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(D), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(X), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(L) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(X), Integer.valueOf(G),
                        Integer.valueOf(H), Integer.valueOf(E), Integer.valueOf(F), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(R), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(L), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(D) },
                { Integer.valueOf(H), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(W), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(A), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(R),
                        Integer.valueOf(S), Integer.valueOf(T), Integer.valueOf(Q), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(N), Integer.valueOf(Z) },
                { Integer.valueOf(N), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(A), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(W), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(T),
                        Integer.valueOf(Q), Integer.valueOf(R), Integer.valueOf(S), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(H), Integer.valueOf(Z) },
                { Integer.valueOf(W), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(N), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(H), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(S),
                        Integer.valueOf(T), Integer.valueOf(Q), Integer.valueOf(R), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(A), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(K), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(O), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(S), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(G), Integer.valueOf(Z), Integer.valueOf(V),
                        Integer.valueOf(W), Integer.valueOf(X), Integer.valueOf(U) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(S), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(G), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(K), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(O), Integer.valueOf(Z), Integer.valueOf(X),
                        Integer.valueOf(U), Integer.valueOf(V), Integer.valueOf(W) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(O), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(S), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(G), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(K), Integer.valueOf(Z), Integer.valueOf(W),
                        Integer.valueOf(X), Integer.valueOf(U), Integer.valueOf(V) },
                { Integer.valueOf(B), Integer.valueOf(C), Integer.valueOf(D), Integer.valueOf(A), Integer.valueOf(Q),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(T), Integer.valueOf(E),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(H), Integer.valueOf(I),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(L), Integer.valueOf(M),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(P), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(D), Integer.valueOf(A), Integer.valueOf(B), Integer.valueOf(C), Integer.valueOf(I),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(L), Integer.valueOf(M),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(P), Integer.valueOf(Q),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(T), Integer.valueOf(E),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(H), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(C), Integer.valueOf(D), Integer.valueOf(A), Integer.valueOf(B), Integer.valueOf(M),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(P), Integer.valueOf(Q),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(T), Integer.valueOf(E),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(H), Integer.valueOf(I),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(L), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(O), Integer.valueOf(P), Integer.valueOf(Z), Integer.valueOf(B),
                        Integer.valueOf(C), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(J),
                        Integer.valueOf(K), Integer.valueOf(L), Integer.valueOf(I), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(X), Integer.valueOf(U), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(F),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(E) },
                { Integer.valueOf(Z), Integer.valueOf(E), Integer.valueOf(F), Integer.valueOf(Z), Integer.valueOf(X),
                        Integer.valueOf(U), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(L),
                        Integer.valueOf(I), Integer.valueOf(J), Integer.valueOf(K), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(B), Integer.valueOf(C), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(P),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(O) },
                { Integer.valueOf(Z), Integer.valueOf(X), Integer.valueOf(U), Integer.valueOf(Z), Integer.valueOf(O),
                        Integer.valueOf(P), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(K),
                        Integer.valueOf(L), Integer.valueOf(I), Integer.valueOf(J), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(E), Integer.valueOf(F), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(C),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(B) },
                { Integer.valueOf(S), Integer.valueOf(T), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(A),
                        Integer.valueOf(B), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(N),
                        Integer.valueOf(O), Integer.valueOf(P), Integer.valueOf(M), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(U), Integer.valueOf(V), Integer.valueOf(I),
                        Integer.valueOf(J), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(I), Integer.valueOf(J), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(U),
                        Integer.valueOf(V), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(P),
                        Integer.valueOf(M), Integer.valueOf(N), Integer.valueOf(O), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(A), Integer.valueOf(B), Integer.valueOf(S),
                        Integer.valueOf(T), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(U), Integer.valueOf(V), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(S),
                        Integer.valueOf(T), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(O),
                        Integer.valueOf(P), Integer.valueOf(M), Integer.valueOf(N), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(I), Integer.valueOf(J), Integer.valueOf(A),
                        Integer.valueOf(B), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(K), Integer.valueOf(L), Integer.valueOf(F),
                        Integer.valueOf(G), Integer.valueOf(H), Integer.valueOf(E), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(W), Integer.valueOf(X), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(C),
                        Integer.valueOf(D), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Q), Integer.valueOf(R) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Q), Integer.valueOf(R), Integer.valueOf(H),
                        Integer.valueOf(E), Integer.valueOf(F), Integer.valueOf(G), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(C), Integer.valueOf(D), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(W),
                        Integer.valueOf(X), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(K), Integer.valueOf(L) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(W), Integer.valueOf(X), Integer.valueOf(G),
                        Integer.valueOf(H), Integer.valueOf(E), Integer.valueOf(F), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Q), Integer.valueOf(R), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(K),
                        Integer.valueOf(L), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(C), Integer.valueOf(D) },
                { Integer.valueOf(H), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(G), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(V), Integer.valueOf(W), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(D),
                        Integer.valueOf(A), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(R),
                        Integer.valueOf(S), Integer.valueOf(T), Integer.valueOf(Q), Integer.valueOf(Z),
                        Integer.valueOf(M), Integer.valueOf(N), Integer.valueOf(Z) },
                { Integer.valueOf(N), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(M), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(D), Integer.valueOf(A), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(V),
                        Integer.valueOf(W), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(T),
                        Integer.valueOf(Q), Integer.valueOf(R), Integer.valueOf(S), Integer.valueOf(Z),
                        Integer.valueOf(G), Integer.valueOf(H), Integer.valueOf(Z) },
                { Integer.valueOf(W), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(V), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(M), Integer.valueOf(N), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(G),
                        Integer.valueOf(H), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(S),
                        Integer.valueOf(T), Integer.valueOf(Q), Integer.valueOf(R), Integer.valueOf(Z),
                        Integer.valueOf(D), Integer.valueOf(A), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(J), Integer.valueOf(K), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(N), Integer.valueOf(O), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(R), Integer.valueOf(S), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(F), Integer.valueOf(G), Integer.valueOf(Z), Integer.valueOf(V),
                        Integer.valueOf(W), Integer.valueOf(X), Integer.valueOf(U) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(R), Integer.valueOf(S), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(F), Integer.valueOf(G), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(J), Integer.valueOf(K), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(N), Integer.valueOf(O), Integer.valueOf(Z), Integer.valueOf(X),
                        Integer.valueOf(U), Integer.valueOf(V), Integer.valueOf(W) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(N), Integer.valueOf(O), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(R), Integer.valueOf(S), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(F), Integer.valueOf(G), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(J), Integer.valueOf(K), Integer.valueOf(Z), Integer.valueOf(W),
                        Integer.valueOf(X), Integer.valueOf(U), Integer.valueOf(V) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(T), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(H), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(L), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(P), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(L), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(P), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(T), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(H), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(P), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(T), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(H), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(L), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(O), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(B),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(X), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(E) },
                { Integer.valueOf(Z), Integer.valueOf(E), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(X),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(B), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(O) },
                { Integer.valueOf(Z), Integer.valueOf(X), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(O),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(E), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(B) },
                { Integer.valueOf(S), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(A),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(U), Integer.valueOf(Z), Integer.valueOf(I),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(I), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(U),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(A), Integer.valueOf(Z), Integer.valueOf(S),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(U), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(S),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(I), Integer.valueOf(Z), Integer.valueOf(A),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(K), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(W), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(C),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Q), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Q), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(C), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(W),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(K), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(W), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Q), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(K),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(C), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(G), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(V), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(D),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(M), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(M), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(D), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(V),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(G), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(V), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(M), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(G),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(D), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(J), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(N), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(R), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(F), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(R), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(F), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(J), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(N), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(N), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(R), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(F), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(J), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z),
                        Integer.valueOf(Z), Integer.valueOf(Z), Integer.valueOf(Z) },
                { Integer.valueOf(S), Integer.valueOf(T), Integer.valueOf(Q), Integer.valueOf(R), Integer.valueOf(H),
                        Integer.valueOf(E), Integer.valueOf(F), Integer.valueOf(G), Integer.valueOf(A),
                        Integer.valueOf(B), Integer.valueOf(C), Integer.valueOf(D), Integer.valueOf(N),
                        Integer.valueOf(O), Integer.valueOf(P), Integer.valueOf(M), Integer.valueOf(W),
                        Integer.valueOf(X), Integer.valueOf(U), Integer.valueOf(V), Integer.valueOf(I),
                        Integer.valueOf(J), Integer.valueOf(K), Integer.valueOf(L) },
                { Integer.valueOf(I), Integer.valueOf(J), Integer.valueOf(K), Integer.valueOf(L), Integer.valueOf(F),
                        Integer.valueOf(G), Integer.valueOf(H), Integer.valueOf(E), Integer.valueOf(U),
                        Integer.valueOf(V), Integer.valueOf(W), Integer.valueOf(X), Integer.valueOf(P),
                        Integer.valueOf(M), Integer.valueOf(N), Integer.valueOf(O), Integer.valueOf(C),
                        Integer.valueOf(D), Integer.valueOf(A), Integer.valueOf(B), Integer.valueOf(S),
                        Integer.valueOf(T), Integer.valueOf(Q), Integer.valueOf(R) },
                { Integer.valueOf(U), Integer.valueOf(V), Integer.valueOf(W), Integer.valueOf(X), Integer.valueOf(G),
                        Integer.valueOf(H), Integer.valueOf(E), Integer.valueOf(F), Integer.valueOf(S),
                        Integer.valueOf(T), Integer.valueOf(Q), Integer.valueOf(R), Integer.valueOf(O),
                        Integer.valueOf(P), Integer.valueOf(M), Integer.valueOf(N), Integer.valueOf(K),
                        Integer.valueOf(L), Integer.valueOf(I), Integer.valueOf(J), Integer.valueOf(A),
                        Integer.valueOf(B), Integer.valueOf(C), Integer.valueOf(D) },
                { Integer.valueOf(B), Integer.valueOf(C), Integer.valueOf(D), Integer.valueOf(A), Integer.valueOf(Q),
                        Integer.valueOf(R), Integer.valueOf(S), Integer.valueOf(T), Integer.valueOf(E),
                        Integer.valueOf(F), Integer.valueOf(G), Integer.valueOf(H), Integer.valueOf(I),
                        Integer.valueOf(J), Integer.valueOf(K), Integer.valueOf(L), Integer.valueOf(M),
                        Integer.valueOf(N), Integer.valueOf(O), Integer.valueOf(P), Integer.valueOf(X),
                        Integer.valueOf(U), Integer.valueOf(V), Integer.valueOf(W) },
                { Integer.valueOf(D), Integer.valueOf(A), Integer.valueOf(B), Integer.valueOf(C), Integer.valueOf(I),
                        Integer.valueOf(J), Integer.valueOf(K), Integer.valueOf(L), Integer.valueOf(M),
                        Integer.valueOf(N), Integer.valueOf(O), Integer.valueOf(P), Integer.valueOf(Q),
                        Integer.valueOf(R), Integer.valueOf(S), Integer.valueOf(T), Integer.valueOf(E),
                        Integer.valueOf(F), Integer.valueOf(G), Integer.valueOf(H), Integer.valueOf(V),
                        Integer.valueOf(W), Integer.valueOf(X), Integer.valueOf(U) },
                { Integer.valueOf(C), Integer.valueOf(D), Integer.valueOf(A), Integer.valueOf(B), Integer.valueOf(M),
                        Integer.valueOf(N), Integer.valueOf(O), Integer.valueOf(P), Integer.valueOf(Q),
                        Integer.valueOf(R), Integer.valueOf(S), Integer.valueOf(T), Integer.valueOf(E),
                        Integer.valueOf(F), Integer.valueOf(G), Integer.valueOf(H), Integer.valueOf(I),
                        Integer.valueOf(J), Integer.valueOf(K), Integer.valueOf(L), Integer.valueOf(W),
                        Integer.valueOf(X), Integer.valueOf(U), Integer.valueOf(V) },
                { Integer.valueOf(N), Integer.valueOf(O), Integer.valueOf(P), Integer.valueOf(M), Integer.valueOf(B),
                        Integer.valueOf(C), Integer.valueOf(D), Integer.valueOf(A), Integer.valueOf(J),
                        Integer.valueOf(K), Integer.valueOf(L), Integer.valueOf(I), Integer.valueOf(V),
                        Integer.valueOf(W), Integer.valueOf(X), Integer.valueOf(U), Integer.valueOf(T),
                        Integer.valueOf(Q), Integer.valueOf(R), Integer.valueOf(S), Integer.valueOf(F),
                        Integer.valueOf(G), Integer.valueOf(H), Integer.valueOf(E) },
                { Integer.valueOf(H), Integer.valueOf(E), Integer.valueOf(F), Integer.valueOf(G), Integer.valueOf(X),
                        Integer.valueOf(U), Integer.valueOf(V), Integer.valueOf(W), Integer.valueOf(L),
                        Integer.valueOf(I), Integer.valueOf(J), Integer.valueOf(K), Integer.valueOf(D),
                        Integer.valueOf(A), Integer.valueOf(B), Integer.valueOf(C), Integer.valueOf(R),
                        Integer.valueOf(S), Integer.valueOf(T), Integer.valueOf(Q), Integer.valueOf(P),
                        Integer.valueOf(M), Integer.valueOf(N), Integer.valueOf(O) },
                { Integer.valueOf(W), Integer.valueOf(X), Integer.valueOf(U), Integer.valueOf(V), Integer.valueOf(O),
                        Integer.valueOf(P), Integer.valueOf(M), Integer.valueOf(N), Integer.valueOf(K),
                        Integer.valueOf(L), Integer.valueOf(I), Integer.valueOf(J), Integer.valueOf(G),
                        Integer.valueOf(H), Integer.valueOf(E), Integer.valueOf(F), Integer.valueOf(S),
                        Integer.valueOf(T), Integer.valueOf(Q), Integer.valueOf(R), Integer.valueOf(C),
                        Integer.valueOf(D), Integer.valueOf(A), Integer.valueOf(B) } };"""

# Apply the replacement

def main():
    output_text = replace_integer_value_of(input_text)
    pyperclip.copy(output_text)

if __name__ == "__main__":
    main()  