# The buffers to use - uncomment the ones you want
use_edge_buffers:
  # - UF # Standard UF buffer
  # - FU
  # - DF
  - UR

use_corner_buffers:
  # - UFR
  - UBL
  # - UFL
  # - RDF

use_wing_buffers:
  - UFr
  - DFr
  # - FUr

use_xcenter_buffers:
  - Ufr
  - Ubl
  - Ubr
  - Ufl

use_tcenter_buffers:
  - Uf
  - Ub
  - Ur
  - Ul

# Scramble types to generate - set True/False for each type
generate:
  3bld: true # Full 3x3 BLD scrambles
  4bld: true # Full 4x4 BLD scrambles
  5bld: true # Full 5x5 BLD scrambles
  edges_only: true # 3x3 edges-only scrambles
  corners_only: true # 3x3 corners-only scrambles
  4bld_centers_only: true # 4x4 centers-only scrambles
  4bld_wings_only: true # 4x4 wings-only scrambles
  5bld_edges_corners: true # 5x5 edges+corners (5edge) scrambles

# Scramble counts for each type
counts:
  3bld: 1000000 # Scrambles per 3BLD combo
  4bld: 600000 # Scrambles per 4BLD combo
  5bld: 600000 # Scrambles per 5BLD combo
  edges_only: 350000 # Scrambles per edges-only combo
  corners_only: 350000 # Scrambles per corners-only combo
  4bld_centers_only: 200000 # Scrambles per 4BLD centers combo
  4bld_wings_only: 200000 # Scrambles per 4BLD wings combo
  5bld_edges_corners: 200000 # Scrambles per 5BLD edges+corners combo

# Specific combinations to generate (if empty, will use all combinations from above)
specific_combinations:

  3bld:
    - edge_buffer: UF # 3style
      corner_buffer: UFR
    - edge_buffer: UR # OP/OP
      corner_buffer: UBL
    - edge_buffer: DF # M2/OP
      corner_buffer: UBL
  4bld:
    - corner_buffer: UFR
      wing_buffer: UFr
      xcenter_buffer: Ufr
    - corner_buffer: UFR
      wing_buffer: UFr
      xcenter_buffer: Ubl
    - corner_buffer: UBL
      wing_buffer: DFr
      xcenter_buffer: Ubl

  edges_only:
    - edge_buffer: UR
    - edge_buffer: UF
  corners_only:
    - corner_buffer: UBL
    - corner_buffer: UFR
  4bld_centers_only:
    - xcenter_buffer: Ufr
    - xcenter_buffer: Ubl
  4bld_wings_only:
    - wing_buffer: UFr
    - wing_buffer: DFr

  5bld_edges_corners:
    - edge_buffer: UF
      wing_buffer: UFr
      corner_buffer: UFR
    - edge_buffer: UF
      wing_buffer: UFr
      corner_buffer: UBL
  5bld:
    - edge_buffer: UF
      corner_buffer: UFR
      wing_buffer: UFr
      xcenter_buffer: Ufr
      tcenter_buffer: Uf
    - edge_buffer: UF
      corner_buffer: UFR
      wing_buffer: UFr
      xcenter_buffer: Ubl
      tcenter_buffer: Ub
      
    - edge_buffer: DF
      corner_buffer: UBL
      wing_buffer: DFr
      xcenter_buffer: Ubl
      tcenter_buffer: Ub

# Backup configuration
backup:
  enabled: true # Whether to create backups at all
  sqlite_backup: true # Whether to create SQLite backup
