version: '3.8'

services:
  scramble-generator:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/scramble_generation
      - ./db_solves:/app/scramble_generation/db_solves
      - ./txt_files:/app/scramble_generation/txt_files
    environment:
      - PYTHONUNBUFFERED=1
      - JAVA_HOME=/usr/lib/jvm/temurin-21-jdk-amd64
      - DB_NAME=all_solves_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    tty: true
    stdin_open: true

  db:
    build:
      context: ../CustomBLD/custombld_db
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: 